name: CIT Badger

on:
  workflow_call:

concurrency:
  group: cit-badger-${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  badger:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [v1, v2]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23.x

      - name: Install prom2json
        run: go install github.com/prometheus/prom2json/cmd/prom2json@latest
        env:
          GOBIN: /usr/local/bin

      - name: Prepare Metrics Output Directory
        run: mkdir -p ./metrics_output

      - name: Run Badger storage integration tests
        run: |
          case ${{ matrix.version }} in
            v1)
              make badger-storage-integration-test
              ;;
            v2)
              STORAGE=badger make jaeger-v2-storage-integration-test







