name: Workflow B

on:
  workflow_call:

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step in Workflow B
        run: echo "This is Workflow B, only called by Workflow A."
